### ISSUE TITLE
Exception coming on npm run start  

### ISSUE THREAD

**Issue by ankitPagalGuy** [gokulkrishh/demo-progressive-web-app#5]
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:890:11)
    at exports._exceptionWithHostPort (util.js:913:20)
    at Server._listen2 (net.js:1234:14)
    at listen (net.js:1270:10)
    at Server.listen (net.js:1366:5)
    at EventEmitter.listen (/Users/techteam/Pwa/demo-progressive-web-app/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (/Users/techteam/Pwa/demo-progressive-web-app/server.js:51:5)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)

**Comment by gokulkrishh** [comment]
@ankitPagalGuy This error is due to you are running an another server in same port i.e: 3000 port. Either kill the process or change the port number to different in **demo-progressive-web-app**
